### ISSUE TITLE
投胎不行呀

### ISSUE THREAD

**Issue by HowToLoveChina** [oiuv/mud#24]
```
#define __VERSION__ "fluffos v2019.2020091001"
```
运行的版本是v2019，在运行完washto，然后做born 扬州人氏　或其他任何家族，均立即停止响应，cpu占用也不高
但是长时间无返馈，查看debug.log也没有任何结果。

这个问题从哪里开始查呢?

打开调试模式后，发现输入的　氏　是乱码，复制后再输入进去也不行。看来xfce终端可能不适用于mud

**Comment by oiuv** [comment]
测试没有任何问题呀，你用zmud/mudlet/mush/tintin++这些客户端试试呢？

**Comment by HowToLoveChina** [comment]
用tintin++就好了，应该是字符集问题
